# Generated by Django 5.2.5 on 2025-11-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('value', models.FloatField(verbose_name='valor')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='registrado en')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
