# Generated by Django 5.2.5 on 2025-11-22 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='metric',
            options={'ordering': ['category__name', 'name']},
        ),
        migrations.AddField(
            model_name='metric',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metric',
            name='display_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='metric',
            name='unit',
            field=models.CharField(default='unit', max_length=30),
        ),
        migrations.AlterField(
            model_name='metric',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('detail', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_logentries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        # Añadimos el campo 'category' como nullable primero para evitar problemas
        migrations.AddField(
            model_name='metric',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metrics', to='dashboard.metriccategory'),
        ),
        # Rellenar valores nulos con una categoría por defecto (si existen métricas previas)
        migrations.RunPython(
            code=(lambda apps, schema_editor: (
                __import__('django').db.transaction.atomic().__enter__(),
                (lambda MetricCategory, Metric: (
                    MetricCategory.objects.get_or_create(name='default', defaults={'description': 'Categoría creada por migración para registros existentes'})[0],
                    Metric.objects.filter(category__isnull=True).update(category=MetricCategory.objects.get(name='default'))
                ))(apps.get_model('dashboard', 'MetricCategory'), apps.get_model('dashboard', 'Metric')),
                __import__('django').db.transaction.atomic().__exit__(None, None, None)
            )),
            reverse_code=migrations.RunPython.noop,
        ),
        # Hacemos el campo obligatorio ahora que los registros existentes tienen categoría
        migrations.AlterField(
            model_name='metric',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metrics', to='dashboard.metriccategory'),
        ),
        migrations.AlterUniqueTogether(
            name='metric',
            unique_together={('name', 'category')},
        ),
        migrations.CreateModel(
            name='MetricValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='dashboard.metric')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='metric',
            name='recorded_at',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='value',
        ),
    ]
