# Generated by Django 5.2.5 on 2025-11-24 19:30

from django.db import migrations, models


def populate_slugs(apps, schema_editor):
    Metric = apps.get_model('dashboard', 'Metric')
    from django.utils.text import slugify as _slugify
    for m in Metric.objects.all():
        try:
            current = getattr(m, 'slug', None)
        except Exception:
            current = None
        if current:
            continue
        base = _slugify(m.name) or 'metric'
        slug = base
        i = 1
        while Metric.objects.filter(slug=slug).exists():
            slug = f"{base}-{i}"
            i += 1
        m.slug = slug
        m.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_fix_default_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='chart_type',
            field=models.CharField(choices=[('line', 'Line'), ('bar', 'Bar'), ('area', 'Area'), ('pie', 'Pie')], default='line', max_length=20),
        ),
        migrations.AddField(
            model_name='metric',
            name='default_granularity',
            field=models.CharField(default='daily', max_length=10),
        ),
        migrations.AddField(
            model_name='metric',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, null=True),
        ),
        migrations.RunPython(populate_slugs, reverse_code=migrations.RunPython.noop),
        # After populating slugs, enforce uniqueness/non-null
        migrations.AlterField(
            model_name='metric',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True, null=False),
        ),
        migrations.AddField(
            model_name='metric',
            name='visible_on_dashboard',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='DashboardView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('default_granularity', models.CharField(default='daily', max_length=10)),
                ('default_from', models.DateField(blank=True, null=True)),
                ('default_to', models.DateField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('metrics', models.ManyToManyField(blank=True, related_name='dashboard_views', to='dashboard.metric')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
